### PR TITLE
Bump to v2.4.5

### PR DESCRIPTION
**Pull request by nstepien**

### CODE REVIEW

**Comment by oohnoitz** [comment]
Might want to do https://docs.npmjs.com/cli/deprecate while you are at it.

**Comment by nstepien** [comment]
Yup that's what I'm planning on doing.

**Comment by silverwind** [comment]
Is v10.16.0 correct? [zlib docs](https://nodejs.org/dist/latest/docs/api/zlib.html#zlib_zlib_brotlicompress_buffer_options_callback) say it came in v11.7.0.

**Comment by nstepien** [comment]
IIRC it was first introduced in v11.7.0, and was the backported to Node.js v10.
I got this version from the `v10.16.0` from the v10 docs:
https://nodejs.org/dist/latest-v10.x/docs/api/zlib.html#zlib_zlib_brotlicompress_buffer_options_callback

**Comment by silverwind** [comment]
Ah you're [correct](https://github.com/nodejs/node/blob/v10.x/doc/changelogs/CHANGELOG_V10.md#2019-05-28-version-10160-dubnium-lts-bethgriggs).

**Pull request merged**
